-- =====================================================================
-- Migration: 002 財務核心 8 表
-- 檔案:     002_finance_core_tables.sql
-- 日期:     2026-09-03 04:59:05
-- 資料庫:   MySQL 8.x / ERMM_db
-- 表數:     8 張
-- 目的:     批次管線 Step7 的目標表 + 日常 CRUD 頁面全部讀這幾張
--
-- 使用方式:
--   mysql -hlocalhost -uroot -pERMM_db < 002_finance_core_tables.sql
--
-- 回滾:
--   mysql -hlocalhost -uroot -pERMM_db < 002_finance_core_tables_rollback.sql
-- =====================================================================

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- 版本追蹤
CREATE TABLE IF NOT EXISTS schema_migrations (
    version VARCHAR(50) PRIMARY KEY,
    applied_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    description VARCHAR(200)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `mgm_finance_summary` (
  `uid` int NOT NULL AUTO_INCREMENT,
  `bu_no` varchar(20) NOT NULL,
  `YYYY_MM` varchar(10) NOT NULL COMMENT '年月 2026/09',
  `YYYY` varchar(10) DEFAULT NULL,
  `MM` varchar(5) DEFAULT NULL,
  `flag` varchar(10) DEFAULT NULL,
  `cash_amt` decimal(18,2) DEFAULT '0.00' COMMENT '現金',
  `deposite_amt` decimal(18,2) DEFAULT '0.00' COMMENT '銀行存款',
  `interest_amt` decimal(18,2) DEFAULT '0.00' COMMENT '應收利息',
  `AR_amt` decimal(18,2) DEFAULT '0.00' COMMENT '應收帳款',
  `AR_bill_amt` decimal(18,2) DEFAULT '0.00' COMMENT '應收票據',
  `AR_debet_amt` decimal(18,2) DEFAULT '0.00' COMMENT '應收借項',
  `AR_temp_amt` decimal(18,2) DEFAULT '0.00' COMMENT '暫收款',
  `AR_affiliate_amt` decimal(18,2) DEFAULT '0.00' COMMENT '關係人應收',
  `AR_other_amt` decimal(18,2) DEFAULT '0.00' COMMENT '其他應收',
  `AR_dividend_amt` decimal(18,2) DEFAULT '0.00' COMMENT '應收股利',
  `stock_P_amt` decimal(18,2) DEFAULT '0.00' COMMENT '製成品存貨',
  `stock_M_amt` decimal(18,2) DEFAULT '0.00' COMMENT '原料存貨',
  `stock_S_amt` decimal(18,2) DEFAULT '0.00' COMMENT '副料存貨',
  `stock_transit_amt` decimal(18,2) DEFAULT '0.00' COMMENT '在途存貨',
  `stock_value_amt` decimal(18,2) DEFAULT '0.00' COMMENT '存貨價值合計',
  `WIP_M_amt` decimal(18,2) DEFAULT '0.00' COMMENT '在製品-材料',
  `WIP_labor_amt` decimal(18,2) DEFAULT '0.00' COMMENT '在製品-人工',
  `WIP_EXP_amt` decimal(18,2) DEFAULT '0.00' COMMENT '在製品-費用',
  `reserve_loss_amt` decimal(18,2) DEFAULT '0.00' COMMENT '備抵損失(減項)',
  `prepay_EXP_amt` decimal(18,2) DEFAULT '0.00' COMMENT '預付設備',
  `prepay_goods_amt` decimal(18,2) DEFAULT '0.00' COMMENT '預付貨款',
  `LQ_prepay_EQMT_amt` decimal(18,2) DEFAULT '0.00' COMMENT '流動預付設備',
  `building_amt` decimal(18,2) DEFAULT '0.00' COMMENT '房屋及建築',
  `acc_de_building` decimal(18,2) DEFAULT '0.00' COMMENT '房屋累計折舊',
  `equipment_amt` decimal(18,2) DEFAULT '0.00' COMMENT '機器設備',
  `acc_de_EQMT` decimal(18,2) DEFAULT '0.00' COMMENT '設備累計折舊',
  `vehicle_amt` decimal(18,2) DEFAULT '0.00' COMMENT '運輸設備',
  `acc_de_vehicle` decimal(18,2) DEFAULT '0.00' COMMENT '車輛累計折舊',
  `office_amt` decimal(18,2) DEFAULT '0.00' COMMENT '辦公設備',
  `acc_de_office` decimal(18,2) DEFAULT '0.00' COMMENT '辦公累計折舊',
  `intangible_amt` decimal(18,2) DEFAULT '0.00' COMMENT '無形資產',
  `LQ_asset_amt` decimal(18,2) DEFAULT '0.00' COMMENT '流動資產合計',
  `FX_asset_amt` decimal(18,2) DEFAULT '0.00' COMMENT '非流動資產合計',
  `other_asset_amt` decimal(18,2) DEFAULT '0.00' COMMENT '其他資產',
  `ttl_asset_amt` decimal(18,2) DEFAULT '0.00' COMMENT '資產總額',
  `current_asset_amt` decimal(18,2) DEFAULT '0.00',
  `non_current_asset_amt` decimal(18,2) DEFAULT '0.00',
  `loan_amt` decimal(18,2) DEFAULT '0.00' COMMENT '短期借款',
  `AP_amt` decimal(18,2) DEFAULT '0.00' COMMENT '應付帳款',
  `AP_tax_amt` decimal(18,2) DEFAULT '0.00' COMMENT '應付稅費',
  `AP_salary_amt` decimal(18,2) DEFAULT '0.00' COMMENT '應付薪資',
  `AP_other_amt` decimal(18,2) DEFAULT '0.00' COMMENT '其他應付',
  `deposit_liab_amt` decimal(18,2) DEFAULT '0.00' COMMENT '預收款項',
  `LT_loan_amt` decimal(18,2) DEFAULT '0.00' COMMENT '長期借款',
  `LT_debet_amt` decimal(18,2) DEFAULT '0.00' COMMENT '長期負債合計',
  `LQ_debet_amt` decimal(18,2) DEFAULT '0.00' COMMENT '流動負債合計',
  `debet_amt` decimal(18,2) DEFAULT '0.00' COMMENT '負債總額',
  `captial_stock` decimal(18,2) DEFAULT '0.00' COMMENT '股本',
  `captial_reserve` decimal(18,2) DEFAULT '0.00' COMMENT '資本公積',
  `legal_reserve` decimal(18,2) DEFAULT '0.00' COMMENT '法定盈餘公積',
  `accumulated_amt` decimal(18,2) DEFAULT '0.00' COMMENT '累積盈餘',
  `current_PL_amt` decimal(18,2) DEFAULT '0.00' COMMENT '本期損益',
  `stockholder_amt` decimal(18,2) DEFAULT '0.00' COMMENT '股東權益合計',
  `ttl_debet_amt` decimal(18,2) DEFAULT '0.00' COMMENT '負債及權益總額',
  `current_debet_amt` decimal(18,2) DEFAULT '0.00',
  `long_term_debet_amt` decimal(18,2) DEFAULT '0.00',
  `sale_amt` decimal(18,2) DEFAULT '0.00' COMMENT '銷貨收入',
  `sale_cost_amt` decimal(18,2) DEFAULT '0.00' COMMENT '銷貨成本',
  `sale_discount_amt` decimal(18,2) DEFAULT '0.00' COMMENT '銷貨折扣',
  `net_sale_amt` decimal(18,2) DEFAULT '0.00' COMMENT '銷貨淨額',
  `sale_exp_amt` decimal(18,2) DEFAULT '0.00' COMMENT '銷售費用',
  `MGM_EXP_amt` decimal(18,2) DEFAULT '0.00' COMMENT '管理費用',
  `finance_EXP_amt` decimal(18,2) DEFAULT '0.00' COMMENT '財務費用',
  `operation_EXP_amt` decimal(18,2) DEFAULT '0.00' COMMENT '營業費用合計',
  `BIZ_other_INC_amt` decimal(18,2) DEFAULT '0.00' COMMENT '營業外收入',
  `others_INC_amt` decimal(18,2) DEFAULT '0.00' COMMENT '其他收入',
  `others_cost_amt` decimal(18,2) DEFAULT '0.00' COMMENT '其他支出',
  `INVEST_profit_amt` decimal(18,2) DEFAULT '0.00' COMMENT '投資收益',
  `AR_subsidy_amt` decimal(18,2) DEFAULT '0.00' COMMENT '補貼收入',
  `BIZ_major_margin_amt` decimal(18,2) DEFAULT '0.00' COMMENT '營業毛利=sale-cost-VAT',
  `BIZ_margin_amt` decimal(18,2) DEFAULT '0.00' COMMENT '營業利益',
  `operation_profit_amt` decimal(18,2) DEFAULT '0.00' COMMENT '營業利潤',
  `pretax_profit_amt` decimal(18,2) DEFAULT '0.00' COMMENT '稅前淨利',
  `net_profit_amt` decimal(18,2) DEFAULT '0.00' COMMENT '淨利',
  `sale_profit` decimal(18,2) DEFAULT '0.00' COMMENT '銷貨利潤',
  `retained_income_amt` decimal(18,2) DEFAULT '0.00' COMMENT '保留盈餘',
  `VAT_rate` decimal(10,4) DEFAULT '0.0000' COMMENT '增值稅率',
  `VAT_amt` decimal(18,2) DEFAULT '0.00' COMMENT '增值稅額',
  `free_tax_sale_amt` decimal(18,2) DEFAULT '0.00' COMMENT '免稅銷售',
  `on_tax_sale_amt` decimal(18,2) DEFAULT '0.00' COMMENT '應稅銷售',
  `on_tax_goods_amt` decimal(18,2) DEFAULT '0.00' COMMENT '應稅貨物',
  `on_tax_service_amt` decimal(18,2) DEFAULT '0.00' COMMENT '應稅勞務',
  `po_tax_out_amt` decimal(18,2) DEFAULT '0.00' COMMENT '進項稅額',
  `AP_tax_deduct_amt` decimal(18,2) DEFAULT '0.00' COMMENT '應付稅抵扣',
  `addon_tax_amt` decimal(18,2) DEFAULT '0.00' COMMENT '附加稅',
  `ttl_tax_simple_amt` decimal(18,2) DEFAULT '0.00' COMMENT '稅額合計',
  `sale_tax_amt` decimal(18,2) DEFAULT '0.00' COMMENT '銷項稅額',
  `cash_begin_amt` decimal(18,2) DEFAULT '0.00' COMMENT '期初現金',
  `cash_operation_in` decimal(18,2) DEFAULT '0.00' COMMENT '營業活動現金流入',
  `cash_operation_out` decimal(18,2) DEFAULT '0.00' COMMENT '營業活動現金流出',
  `cash_invest_in` decimal(18,2) DEFAULT '0.00' COMMENT '投資活動現金流入',
  `cash_invest_out` decimal(18,2) DEFAULT '0.00' COMMENT '投資活動現金流出',
  `cash_finance_in` decimal(18,2) DEFAULT '0.00' COMMENT '籌資活動現金流入',
  `cash_finance_out` decimal(18,2) DEFAULT '0.00' COMMENT '籌資活動現金流出',
  `cash_end_amt` decimal(18,2) DEFAULT '0.00' COMMENT '期末現金',
  `Z_X1` decimal(18,4) DEFAULT '0.0000' COMMENT '(流動資產-流動負債)/總資產',
  `Z_X2` decimal(18,4) DEFAULT '0.0000' COMMENT '保留盈餘/總資產',
  `Z_X3` decimal(18,4) DEFAULT '0.0000' COMMENT '營業利潤/總資產',
  `Z_X4` decimal(18,4) DEFAULT '0.0000' COMMENT '(股本+特別股)/總負債',
  `Z_X5` decimal(18,4) DEFAULT '0.0000' COMMENT '銷貨收入/總資產',
  `Z_score` decimal(18,4) DEFAULT '0.0000' COMMENT 'Z-Score',
  `Z2_score` decimal(18,4) DEFAULT '0.0000' COMMENT 'Z2-Score(私人公司)',
  `Z3_score` decimal(18,4) DEFAULT '0.0000' COMMENT 'Z3-Score(非製造業)',
  `BZ_X1` decimal(18,4) DEFAULT '0.0000',
  `BZ_X2` decimal(18,4) DEFAULT '0.0000',
  `BZ_X3` decimal(18,4) DEFAULT '0.0000',
  `BZ_X4` decimal(18,4) DEFAULT '0.0000',
  `BZ_X5` decimal(18,4) DEFAULT '0.0000',
  `BZ_model` decimal(18,4) DEFAULT '0.0000' COMMENT 'BZ 破產概率',
  `JZ_ZA` decimal(18,4) DEFAULT '0.0000',
  `JZ_ZB` decimal(18,4) DEFAULT '0.0000',
  `JZ_ZC` decimal(18,4) DEFAULT '0.0000',
  `JZ_ZD` decimal(18,4) DEFAULT '0.0000',
  `JZ_model` decimal(18,4) DEFAULT '0.0000' COMMENT 'JZ 營運能力',
  `wall_mode` varchar(20) DEFAULT NULL COMMENT 'Wolf 模型結果',
  `risk_color` varchar(10) DEFAULT NULL COMMENT '風險燈號 RED/YELLOW/GREEN',
  `current_ratio` decimal(18,4) DEFAULT '0.0000' COMMENT '流動比率',
  `quick_ratio` decimal(18,4) DEFAULT '0.0000' COMMENT '速動比率',
  `debt_ratio` decimal(18,4) DEFAULT '0.0000' COMMENT '負債比率',
  `ROI` decimal(18,4) DEFAULT '0.0000' COMMENT '投資報酬率',
  `ROE` decimal(18,4) DEFAULT '0.0000' COMMENT '股東權益報酬率',
  `ROA` decimal(18,4) DEFAULT '0.0000' COMMENT '資產報酬率',
  `gross_margin` decimal(18,4) DEFAULT '0.0000' COMMENT '毛利率',
  `net_margin` decimal(18,4) DEFAULT '0.0000' COMMENT '淨利率',
  `asset_turnover` decimal(18,4) DEFAULT '0.0000' COMMENT '資產週轉率',
  `inventory_turnover` decimal(18,4) DEFAULT '0.0000' COMMENT '存貨週轉率',
  `receivable_turnover` decimal(18,4) DEFAULT '0.0000' COMMENT '應收帳款週轉率',
  `IRR` decimal(18,4) DEFAULT '0.0000' COMMENT '內部報酬率',
  `employee_cnt` int DEFAULT '0' COMMENT '員工人數',
  `salary_amt` decimal(18,2) DEFAULT '0.00' COMMENT '薪資總額',
  `avg_salary` decimal(18,2) DEFAULT '0.00' COMMENT '平均薪資',
  `exchange_rate` decimal(18,6) DEFAULT '1.000000' COMMENT '當前匯率',
  `batch_id` varchar(50) DEFAULT NULL COMMENT '最後更新批次',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP,
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`uid`),
  UNIQUE KEY `uk_bu_ym` (`bu_no`,`YYYY_MM`),
  KEY `idx_bu_ym` (`bu_no`,`YYYY_MM`),
  KEY `idx_bu_type` (`bu_no`,`flag`)
) ENGINE=InnoDB AUTO_INCREMENT=108 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='財務摘要主表(200+欄位)';

CREATE TABLE IF NOT EXISTS `mgm_casher_details` (
  `uid` int NOT NULL AUTO_INCREMENT,
  `bu_no` varchar(20) NOT NULL,
  `amt_type` varchar(20) DEFAULT NULL COMMENT '收支類型',
  `client_id` varchar(50) DEFAULT NULL,
  `num_vman` varchar(50) NOT NULL COMMENT '發票/收據號碼(唯一)',
  `sub_amt` decimal(18,2) DEFAULT '0.00' COMMENT '金額',
  `DB_CR` varchar(3) NOT NULL COMMENT 'DR=借方(收款)/CR=貸方(付款)',
  `YYYY` varchar(10) DEFAULT NULL,
  `MM` varchar(5) DEFAULT NULL,
  `YYYY_MM` varchar(10) DEFAULT NULL,
  `wk_date` date DEFAULT NULL,
  `bank_acct` varchar(50) DEFAULT NULL COMMENT '銀行帳號',
  `remark` text,
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP,
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`uid`),
  UNIQUE KEY `uk_num_vman` (`bu_no`,`num_vman`),
  KEY `idx_bu_ym` (`bu_no`,`YYYY_MM`),
  KEY `idx_bu_date` (`bu_no`,`wk_date`)
) ENGINE=InnoDB AUTO_INCREMENT=643 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='現金日記帳';

CREATE TABLE IF NOT EXISTS `mgm_invoice_details` (
  `uid` int NOT NULL AUTO_INCREMENT,
  `bu_no` varchar(20) NOT NULL,
  `TX_type` varchar(10) NOT NULL COMMENT 'AR/AP',
  `order_id` varchar(50) DEFAULT NULL COMMENT '訂單編號(SO/PO)',
  `client_id` varchar(50) DEFAULT NULL COMMENT '客戶/供應商',
  `invoice_no` varchar(50) DEFAULT NULL,
  `sub_amt` decimal(18,2) DEFAULT '0.00' COMMENT '金額',
  `tax_type` varchar(20) DEFAULT NULL,
  `tax_rate` decimal(10,4) DEFAULT '0.0000',
  `VAT_amt` decimal(18,2) DEFAULT '0.00',
  `wk_date` date DEFAULT NULL COMMENT '發票日期',
  `pay_date` date DEFAULT NULL COMMENT '付款日期',
  `payment` decimal(18,2) DEFAULT '0.00' COMMENT '已付款',
  `ageing_days` int DEFAULT '0' COMMENT '帳齡天數',
  `DB_CR` varchar(3) DEFAULT NULL COMMENT '借貸別 DR/CR',
  `YYYY_MM` varchar(10) DEFAULT NULL,
  `remark` text,
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP,
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`uid`),
  KEY `idx_bu_tx_inv` (`bu_no`,`TX_type`,`invoice_no`),
  KEY `idx_bu_order` (`bu_no`,`order_id`),
  KEY `idx_bu_ym` (`bu_no`,`YYYY_MM`)
) ENGINE=InnoDB AUTO_INCREMENT=865 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='發票明細表';

CREATE TABLE IF NOT EXISTS `ermm_arap_detail` (
  `uid` int NOT NULL AUTO_INCREMENT,
  `bu_no` varchar(20) NOT NULL COMMENT '業務單位/公司別',
  `YYYY` varchar(10) NOT NULL COMMENT '年度',
  `YYYY_MM` varchar(10) NOT NULL COMMENT '年月 2026/09',
  `AR_amt` decimal(18,2) DEFAULT '0.00' COMMENT '應收帳款',
  `AP_amt` decimal(18,2) DEFAULT '0.00' COMMENT '應付帳款',
  `AR_ageing` decimal(18,2) DEFAULT '0.00' COMMENT '應收帳齡金額',
  `AP_ageing` decimal(18,2) DEFAULT '0.00' COMMENT '應付帳齡金額',
  `batch_id` varchar(50) DEFAULT NULL,
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`uid`),
  UNIQUE KEY `uq_bu_ym` (`bu_no`,`YYYY_MM`),
  KEY `idx_bu_ym` (`bu_no`,`YYYY_MM`),
  KEY `idx_bu` (`bu_no`)
) ENGINE=InnoDB AUTO_INCREMENT=103 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='應收應付彙總表';

CREATE TABLE IF NOT EXISTS `pay_detail` (
  `uid` int NOT NULL AUTO_INCREMENT,
  `bu_no` varchar(20) NOT NULL,
  `supplier_name` varchar(100) DEFAULT NULL,
  `finance_type` varchar(50) DEFAULT NULL COMMENT '費用類型',
  `should_date` date DEFAULT NULL COMMENT '應付日期',
  `invoice_date` date DEFAULT NULL COMMENT '發票日期',
  `amount` decimal(18,2) DEFAULT '0.00',
  `currency_ab` varchar(10) DEFAULT NULL,
  `invoice_num` varchar(50) DEFAULT NULL,
  `pay_date` date DEFAULT NULL COMMENT '付款日期 NULL=未付款',
  `expense_content` text,
  `remark` text,
  `entry_date` date DEFAULT NULL,
  `data_year` varchar(10) DEFAULT NULL,
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP,
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`uid`),
  KEY `idx_bu_pay` (`bu_no`,`invoice_num`),
  KEY `idx_bu_supplier` (`bu_no`,`supplier_name`),
  KEY `idx_bu_date` (`bu_no`,`should_date`)
) ENGINE=InnoDB AUTO_INCREMENT=304 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='付款明細表';

CREATE TABLE IF NOT EXISTS `check_detail` (
  `uid` int NOT NULL AUTO_INCREMENT,
  `bu_no` varchar(20) NOT NULL,
  `check_type` varchar(20) DEFAULT NULL COMMENT '現金支票/轉帳支票',
  `check_num` varchar(50) NOT NULL,
  `company_id` varchar(50) DEFAULT NULL,
  `check_date` date DEFAULT NULL COMMENT '開票日',
  `due_date` date DEFAULT NULL COMMENT '到期日',
  `amount` decimal(18,2) DEFAULT '0.00',
  `to_company` varchar(200) DEFAULT NULL COMMENT '受票單位',
  `bank_acct` varchar(50) DEFAULT NULL,
  `status` varchar(20) DEFAULT '未兌現' COMMENT '未兌現/已兌現/作廢',
  `remark` text,
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP,
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`uid`),
  KEY `idx_bu_check` (`bu_no`,`check_num`),
  KEY `idx_bu_date` (`bu_no`,`check_date`)
) ENGINE=InnoDB AUTO_INCREMENT=41 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='票據明細表';

CREATE TABLE IF NOT EXISTS `mgm_bank_loan_details` (
  `uid` int NOT NULL AUTO_INCREMENT,
  `bu_no` varchar(20) NOT NULL,
  `YYYY` varchar(10) DEFAULT NULL,
  `acct_no` varchar(50) DEFAULT NULL COMMENT '帳戶號碼',
  `type1` varchar(20) DEFAULT NULL COMMENT '存款/貸款/還款',
  `acct_amt` decimal(18,2) DEFAULT '0.00' COMMENT '帳戶金額',
  `unit` varchar(10) DEFAULT NULL COMMENT '幣別',
  `loan_id` varchar(50) DEFAULT NULL COMMENT '借/貸款編號',
  `bank_id` varchar(50) DEFAULT NULL COMMENT '銀行代碼',
  `branch_id` varchar(50) DEFAULT NULL,
  `loan_type` varchar(50) DEFAULT NULL COMMENT '貸款類型',
  `pay_terms` int DEFAULT '0' COMMENT '還款週期(月)',
  `terms_rate` decimal(10,4) DEFAULT '0.0000' COMMENT '利率%',
  `interest_rate` decimal(10,4) DEFAULT '0.0000' COMMENT '利率',
  `begin_date` date DEFAULT NULL COMMENT '起借日期',
  `end_date` date DEFAULT NULL COMMENT '到期日期',
  `pay_days` int DEFAULT '0' COMMENT '距下次利息日天數',
  `payback_amt` decimal(18,2) DEFAULT '0.00' COMMENT '已還本金',
  `loan_amt` decimal(18,2) DEFAULT '0.00' COMMENT '貸款金額',
  `exchange_rate` decimal(18,6) DEFAULT '1.000000' COMMENT '匯率',
  `last_paydate` date DEFAULT NULL COMMENT '上次利息日',
  `next_paydate` date DEFAULT NULL COMMENT '下次利息日',
  `status1` varchar(20) DEFAULT '使用中',
  `loan_desc` text,
  `diff_amt` decimal(18,2) DEFAULT '0.00' COMMENT '匯兌差額',
  `loss_flag` varchar(3) DEFAULT 'N' COMMENT 'Y=匯兌損失',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP,
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`uid`),
  KEY `idx_bu_loan` (`bu_no`,`loan_id`),
  KEY `idx_bu_acct` (`bu_no`,`acct_no`)
) ENGINE=InnoDB AUTO_INCREMENT=19 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='銀行貸款明細表';

CREATE TABLE IF NOT EXISTS `forecast_detail` (
  `uid` int NOT NULL AUTO_INCREMENT,
  `bu_no` varchar(20) NOT NULL,
  `YYYY_MM` varchar(10) NOT NULL,
  `forecast_type` varchar(30) DEFAULT NULL COMMENT '銷售/採購/現金',
  `forecast_amt` decimal(18,2) DEFAULT '0.00',
  `actual_amt` decimal(18,2) DEFAULT '0.00',
  `diff_amt` decimal(18,2) DEFAULT '0.00',
  `remark` text,
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP,
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`uid`),
  KEY `idx_bu_ym_type` (`bu_no`,`YYYY_MM`,`forecast_type`)
) ENGINE=InnoDB AUTO_INCREMENT=68 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='預測明細表';

-- 記錄版本
INSERT IGNORE INTO schema_migrations (version, description) VALUES
('002_mgm_finance_summary', '財務核心 8 表 — mgm_finance_summary'),
('002_mgm_casher_details', '財務核心 8 表 — mgm_casher_details'),
('002_mgm_invoice_details', '財務核心 8 表 — mgm_invoice_details'),
('002_ermm_arap_detail', '財務核心 8 表 — ermm_arap_detail'),
('002_pay_detail', '財務核心 8 表 — pay_detail'),
('002_check_detail', '財務核心 8 表 — check_detail'),
('002_mgm_bank_loan_details', '財務核心 8 表 — mgm_bank_loan_details'),
('002_forecast_detail', '財務核心 8 表 — forecast_detail');

SET FOREIGN_KEY_CHECKS = 1;

-- 驗證
SELECT '=== Migration 002 驗證 ===' AS step;
SELECT TABLE_NAME, TABLE_COMMENT, ENGINE
  FROM information_schema.TABLES
 WHERE TABLE_SCHEMA='ERMM_db'
   AND TABLE_NAME IN ('mgm_finance_summary', 'mgm_casher_details', 'mgm_invoice_details', 'ermm_arap_detail', 'pay_detail', 'check_detail', 'mgm_bank_loan_details', 'forecast_detail')
 ORDER BY TABLE_NAME;
